### ISSUE TITLE
Make non-blocking (Also python3 support)

### ISSUE THREAD

**Issue by aelias36** [rpiRobotics/rpi_ati_net_ft#2]
Right now function calls don't return until the F/T sensor responds. In simple scripts this may be fine, but in more complicated programs this can slow everything down. 

I already have code rewritten to be non-blocking in the following repo:
https://github.com/aelias36/robotic-deep-rolling-gui/tree/main/src/ft_sensor

I will make a pull request soon with these changes. The changes also introduce support for python3.

**Comment by ADS-Facy** [comment]
> Right now function calls don't return until the F/T sensor responds. In simple scripts this may be fine, but in more complicated programs this can slow everything down.
> 
> I already have code rewritten to be non-blocking in the following repo: https://github.com/aelias36/robotic-deep-rolling-gui/tree/main/src/ft_sensor
> 
> I will make a pull request soon with these changes. The changes also introduce support for python3.



Hey, I also wish to use this package and you have made a python3 compatible version. Actually I am unable to read the force data from the sensor. 'ft_wrench' is not getting listed in ROS topic list. All I have done is pasted your code in 'rpi_ati_net_ft.py' script and changed 'python' to 'python3' in shebang line. Can you help out? @aelias36

**Comment by aelias36** [comment]
Does this test code work for you?

https://github.com/aelias36/robotic-deep-rolling-gui/blob/main/src/ft_sensor/test_ft.py

**Comment by ADS-Facy** [comment]
> Does this test code work for you?
> 
> https://github.com/aelias36/robotic-deep-rolling-gui/blob/main/src/ft_sensor/test_ft.py

Thanks for the response. I guess test code is working for me. I dont know whether my procedure is correct or not, because if I run test code individually, I get ('IP address of ATI Net F/T sensor required') but when I launch the file, I can see 'ft_wrench' topic. So overall, my issue has been resolved.

**Comment by aelias36** [comment]
For the test code, it's expecting the IP address as a command line argument.

Since you say it's been resolved, I'll close this issue.
